# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: Applications ・ Solutions
# Description of the Site
description: -- Based On Heart --
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Crestron, RTI, Helvar, more...
# URL for the Image of custom Favicon
favicon-url: /assets/images/logo.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: hi@appcube.com
# facebook_username: /
twitter_username: d8boom
# instagram_username: /
# linkedin_username: /
github_username:  doobom
# youtube_channel_id: /
# reddit_username: /
# behance_username: /
# dribbble_username: /
# spotify_username: /

# Google Analytics
#google-analytics: UA-163806439-1

# Disqus
disqus-shortname: crestronapp

# Name of the Author
author-name: doobom
# URL for the Image of the Author
author-image: /assets/images/doobom.jpeg
# 60 Words About the Author
author-about: Write a bug.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://doobom.me

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "/:category/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
